# Generated by Django 4.2.1 on 2023-05-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('Subject', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
